apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tech-deployment
  labels: 
     app: techapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: techapp

  template:
    metadata:
      labels:
        app: techapp
    spec:
      containers:
      - name: techapp
        image: devops5476/myapp3:4.0-12
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
